version: '3.8'

services:

  python-service:
    build: ./python-app
    container_name: python_service
    ports:
      - "8010:8000"
    command: ./.venv/bin/uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./python-app/app:/home/app/app
    networks:
      - signoz-net
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
      OTEL_EXPORTER_OTLP_INSECURE: true
      OTEL_EXPORTER_CONSOLE: false
      PYTHONUNBUFFERED: 1
  
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q 0.0.0.0:8123/ping || exit 1"]

  kotlin-service:
    build: ./kotlin-app
    container_name: kotlin_service
    ports:
      - "8020:8080"
    networks:
      - signoz-net
    environment:
      OTEL_SERVICE_NAME: kotlin-app
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q 0.0.0.0:8123/ping || exit 1"]

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  signoz-net:
    external: true