version: '3.8'

services:
  
  # ----------------------------
  # Services for the application
  # ----------------------------

  python-service:
    build: ./python-app
    container_name: python_service
    ports:
      - "8010:8000"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    depends_on:
      - collector

  kotlin-service:
    build: ./kotlin-app
    container_name: kotlin_service
    ports:
      - "8020:8080"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    depends_on:
      - collector

  # ----------------------------------
  # OpenTelemetry Collector and SigNoz
  # ----------------------------------

  collector:
    # image: otel/opentelemetry-collector-contrib:latest
    image: signoz/signoz-otel-collector:latest
    container_name: collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./infra/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    depends_on:
      - signoz

  signoz:
    image: signoz/signoz:latest
    container_name: signoz
    ports:
      - "8000:8080"
    depends_on:
      - signoz-db
    environment:
      - SIGNOZ_TELEMETRYSTORE_PROVIDER=clickhouse
      - CLICKHOUSE_DB_HOSTNAME=clickhouse
      - TELEMETRY_ENABLED=true
      - DEPLOYMENT_TYPE=docker-standalone-amd
    volumes:
      - signoz-data:/var/lib/signoz


  # ----------------------------
  # Extra services for the stack
  # ----------------------------

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  signoz-db:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse

volumes:
  mongo-data:
  clickhouse-data:
  signoz-data:
